### ISSUE TITLE
Menu component missing context value

### ISSUE THREAD

**Issue by zanedev** [sanity-io/design#312]
I'm getting various `missing context value` errors when I attempt to use the menu component from the examples in a custom local plugin.  Not sure if I am missing something or if this is a bug.

Example code:
```
import React, { Component } from 'react'
import { PatchEvent, set } from 'part:@sanity/form-builder/patch-event'
import { Box, Select, Menu, MenuItem, Stack, Text, Card, studioTheme, ThemeProvider } from '@sanity/ui'
import styles from './FontAwesome.css'
import icons from './icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
// console.log('icons: ', icons);
function MenuInput({ onChange }) {
  return (
    <Card>
      <Menu
        onItemClick={event => {
          const id = event.target.value;
          const icon = icons.find(icon => icon.id === id)
          const { name, category } = icon;
          const result = {
            id,
            name,
            category,
          };
          return onChange(PatchEvent.from(set(result)))
        }}
      >{
        // eslint-disable-next-line multiline-ternary
        icons.sort((a, b) => a.name.localeCompare(b.name)).map((icon) => {
          const { id, name } = icon;
          return (
            <MenuItem value={id}>
              <Box padding={3}>
                <Stack space={3}>
                  <Text weight="semibold">
                    {name}
                  </Text>
                  <FontAwesomeIcon icon={id} />
                </Stack>
              </Box>
            </MenuItem>
          )
        })
      }
      </Menu>
    </Card>
  );
}
export default class FontAwesomeInput extends Component {
  render() {
    const { onChange } = this.props
    return (
      <ThemeProvider theme={studioTheme}>
        <MenuInput onChange={onChange} />
      </ThemeProvider>
    )
  }
}
```

![image (3)](https://user-images.githubusercontent.com/817344/103468382-bddd9700-4d15-11eb-93c7-57201771a69c.png)

See related thread here:
https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1609009597058600

**Comment by zanedev** [comment]
Any feedback here?

**Comment by athena9** [comment]
I have similar issues with the Autocomplete component

```
Error: useRootTheme(): missing context value
    at useRootTheme (/static/js/app.bundle.js:114508:15)
    at Card (/static/js/app.bundle.js:261255:91)
    at renderWithHooks (/static/js/vendor.bundle.js:17945:18)
    at updateForwardRef (/static/js/vendor.bundle.js:19958:20)
```

**Comment by athena9** [comment]
Although I've Just found the solution on the readme of this repo...

Looks like the components needs to be wrapped in a ThemeProvider HOC, unlike the primitives.

```
import { Button, studioTheme, ThemeProvider} from '@sanity/ui'

return(
  <ThemeProvider theme={studioTheme}>
    <Button>Hello, world</Button>
  </ThemeProvider>
)
```

**Comment by mariuslundgard** [comment]
> I have similar issues with the Autocomplete component

@athena9 Are you using `@sanity/ui` in a Sanity Studio context, or in a custom application? If you're in a Studio, it sounds like there are multiple versions of `@sanity/ui` in play here (which is an issue we're working on making easier to deal with).

**Comment by mariuslundgard** [comment]
> I'm getting various missing context value errors [...]

Thanks for the report @zanedev – looking into it now :)

**Comment by zanedev** [comment]
@mariuslundgard thanks that fixed it!
